### ISSUE TITLE
visual line between num and denom in mathlive editor

### ISSUE THREAD

**Issue by BenetechSchwab** [benetech/MathEditor#49] opened 2017-10-20 19:32 UTC
See screenshot

https://www.evernote.com/l/ABpUo-xyYBtCkKekwPTrRHaRsIX5MdcUWYM

**Comment by NSoiffer** [comment] 2017-10-20 19:52
I've seen occasionally, much more recently. For some reason, the line drops out at certain display sizes. This is something that needs to get fixed in mathlive, and likely will take time. I suggest we change a font size so it doesn't happen in the next few weeks.

**Comment by sueannma** [comment] 2017-10-20 21:20
Neil, do you have suggestions on what to change the font type/size to?

**Comment by NSoiffer** [comment] 2017-10-20 23:02
No. Increasing the font size one step in the browser solves the problem for me.

I see the problem on mathlive.io in Chrome but not Firefox. I filed a bug report there:  https://github.com/arnog/mathlive/issues/26

**Comment by sueannma** [comment] 2017-12-07 00:07
duplicate of issues #59

**Closed** 2017-12-07 00:07 UTC
Labels: bug
